### ISSUE TITLE
Mutiple files read (binout*) not working some times [Python]

### ISSUE THREAD

**Issue by siddhu2310** [PucklaJ/dynareadout#37]
***Issue:***
In some cases, while reading multiple **binout** file, not returning anything.
Not even showing any error.

`Here I have shared my code and binout files.`

[binout0000.zip](https://github.com/PucklaJ/dynareadout/files/13829419/binout0000.zip)

Kindly check the issue.

***Code:***
```python
import numpy as np
# import matplotlib.pyplot as plt
import csv
from dynareadout import Binout

bin_file_path = r"binout*"

def open_binout(file_path):
    bin_file = None
    try:
        bin_file = Binout(file_path)
    except RuntimeError as e:
        print(f"Failed to open binout at {file_path}: {e}")
        exit(1)
    return bin_file


bin_file = open_binout(bin_file_path)

node_ids_displacement = bin_file.read("rbdout/ids")
global_dx = bin_file.read("rbdout/global_dx")

num_timesteps_displacement = len(global_dx)
node_ids_custom = [6, 7]

force_data_array = np.array([[x_disp[n] for x_disp in global_dx] for n in range(len(node_ids_custom))])

result_curve = np.abs(force_data_array[0] - force_data_array[1])
#--------------------------------------------
node_ids_force = bin_file.read("bndout/velocity/rigidbodies/ids")
x_force = bin_file.read("bndout/velocity/rigidbodies/x_force")

num_timesteps_force = len(x_force)
x_force_array = np.array(x_force)


for n, node_id in enumerate(node_ids_force):
    force_data = [x_forc[n] for x_forc in x_force_array]
    # plt.plot(result_curve, force_data, label="Result")

# plt.xlabel('Displacement')
# plt.ylabel('Force')
# plt.legend()
# plt.title('Force vs Displacement')
# plt.show()

csv_data = np.column_stack((result_curve, force_data))
csv_header = ["Displacement", "Force"]

with open("force_vs_displacement.csv", mode="w", newline='') as file:
    writer = csv.writer(file)
    writer.writerow(csv_header)
    writer.writerows(csv_data)
print("File has been Written Successfully")
```

**Comment by PucklaJ** [comment]
Thank you for writing an issue! I was finally able to check it out. It seems that there is a folder called `misc` inside `/bndout/velocity/rigidbodies/d000001`. Opening the binout file crashes because in the folder `d000001` should only be files, but no folders. I thought that folders hold either only files or only folders. It seems that my assumption was wrong. I need to fix this.

**Comment by siddhu2310** [comment]
> Thank you for writing an issue! I was finally able to check it out. It seems that there is a folder called `misc` inside `/bndout/velocity/rigidbodies/d000001`. Opening the binout file crashes because in the folder `d000001` should only be files, but no folders. I thought that folders hold either only files or only folders. It seems that my assumption was wrong. I need to fix this.

Thanks for looking into the issue. I'm working an automation to read binout files.
Kinldy fix the issue as soon as possible.
Thanks in advance.

**Comment by PucklaJ** [comment]
The issue has been resolved. I had to rewrite a huge portion of the binout code. I will just refactor the code and then create a new release

**Comment by siddhu2310** [comment]
> The issue has been resolved. I had to rewrite a huge portion of the binout code. I will just refactor the code and then create a new release

When I can expect the updated one, at least please release the temporary fix.
Since I'm working on the automation, that majorly depends on your module.

**Comment by PucklaJ** [comment]
I will create a new release this week

**Comment by siddhu2310** [comment]
@PucklaJ 
I have checked again, It Keeps crashing to read the files. , Please check with my python code and attached binout files.
