### ISSUE TITLE
Unable to post-process the MATSUM section of a BINOUT file

### ISSUE THREAD

**Issue by mdor30** [PucklaJ/dynareadout#42]
Dear PucklaJ, 

Thank you for this library! I am using it on Python. 

I have some trouble to post-process the MATSUM section of my binout file. When I tried to access any component of the MATSUM file (i.e. the kinetic_energy), I get a Runtime error "RuntimeError: The structure of variable "/matsum/kinetic_energy" is invalid. Time Step 14 differs from the first time step".  

I have checked that the components were well included in the MATSUM section. I have no problem to access to the MATSUM section with LSPrePost. I have no problem to post-process the GLSTAT section or the NODOUT section with your library.

Could you help me on that? 

The binout file can be accessed with: https://filesender.renater.fr/?s=download&token=e96f1f74-74b7-4dba-b541-f6b41b395f98

**Comment by PucklaJ** [comment]
Hello mdor30,

i am having a look at it. Thank you for sending me the binout file this makes it easier to find the error.

**Comment by PucklaJ** [comment]
I fixed the bug. It was caused by `brick_id` suddenly appearing in time step 14 and then disturbing the structure. My code assumed that `kinetic_energy` stays at the same place. The fix will be added in the next release. For the time being here is a workaround:
```python
from dynareadout import Binout

binout = Binout("matsum/binout")

time_steps = binout.get_num_timesteps("matsum")
kinetic_energy = []

for t in range(time_steps):
  d_folder = f"d{t+1:06d}"
  data = binout.read(f"matsum/{d_folder}/kinetic_energy")
  kinetic_energy.append(data)

print(kinetic_energy)
```

**Comment by mdor30** [comment]
Thank you for your help!

**Comment by mdor30** [comment]
With this workaround, how can you access to the part ids in the matsum section?
